LESION:
  LESION_ENABLED: True
  USE_3DCE: True
  # 3*3 = 9 slices in total
  SLICE_NUM: 3
  NUM_IMAGES_3DCE: 9
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/resnet50_caffe.pth'
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.002
  GAMMA: 0.1
  MAX_ITER: 18000
  STEPS: [0, 15000, 17000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  #VIS_ANCHOR: True
  SCALES: (800,)
  MAX_SIZE: 800
  BATCH_SIZE_PER_IM: 32
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCH_SIZE_PER_IM: 32
TEST:
  #SOFT_NMS:
    #ENABLED: True
  SCALE: 800
  MAX_SIZE: 800
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
#VIS: True
#VIS_TH: 0.5
