LESION:
  LESION_ENABLED: True
  USE_3DCE: True
  # 3*3 = 9 slices in total
  SLICE_NUM: 3
  SLICE_INTERVAL: 2.5
  NUM_IMAGES_3DCE: 3
  USE_POSITION: True
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.fpn_ResNet50_conv5_body
  FASTER_RCNN: True
RESNETS:
  IMAGENET_PRETRAINED_WEIGHTS: 'data/pretrained_model/R-50-GN.pkl'
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_gn_transformation  # Note: this is a GN bottleneck transform
  STEM_FUNC: basic_gn_stem  # Note: this is a GN stem
  SHORTCUT_FUNC: basic_gn_shortcut  # Note: this is a GN shortcut
  USE_GN: True
NUM_GPUS: 8
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.002
  GAMMA: 0.1
  MAX_ITER: 18000
  STEPS: [0, 15000, 17000]
FPN:
  FPN_ON: True
  USE_GN: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  RPN_ANCHOR_START_SIZE: 16
FAST_RCNN:
  #ROI_BOX_HEAD: fast_rcnn_heads.roi_2mlp_head
  ROI_BOX_HEAD: fast_rcnn_heads.roi_Xconv1fc_gn_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
TRAIN:
  #VIS_ANCHOR: True
  SCALES: (800,)
  MAX_SIZE: 800
  BATCH_SIZE_PER_IM: 32
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCH_SIZE_PER_IM: 32
  #USE_ADJACENT_LAYER: True
TEST:
  #SOFT_NMS:
    #ENABLED: True
  SCALE: 800
  MAX_SIZE: 800
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
#VIS: True
#VIS_TH: 0.5
